# Generated by Django 3.2.6 on 2021-08-11 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('profile_picture', models.ImageField(blank=True, upload_to='user_profile_pictures')),
                ('tell_us_more_about_yourself', models.TextField(max_length=510)),
                ('user_email', models.EmailField(max_length=254)),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
    ]
