# Generated by Django 3.2.6 on 2021-08-11 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_club_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id',
            new_name='user',
        ),
    ]
