# Generated by Django 3.2.6 on 2021-08-20 21:49

import book_club.account.custom_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookclubuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[book_club.account.custom_validator.validate_len_of_email]),
        ),
    ]
