# Generated by Django 3.2.5 on 2021-08-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=16)),
                ('age', models.IntegerField()),
                ('tell_us_more_about_yourself', models.CharField(max_length=510)),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
