# Generated by Django 3.2.5 on 2021-08-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tell_us_more_about_yourself',
            field=models.TextField(max_length=510),
        ),
    ]
