# Generated by Django 3.2.5 on 2021-08-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('author', models.CharField(max_length=30)),
                ('audiobook', models.BooleanField(default=False)),
                ('length', models.CharField(max_length=10)),
                ('emotional_value', models.TextField(max_length=255)),
                ('review', models.TextField(max_length=1500)),
                ('mark', models.IntegerField()),
            ],
        ),
    ]
