# Generated by Django 3.2.6 on 2021-08-12 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('author', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('non-fiction', 'Non-fiction')], default='None', max_length=11)),
                ('length', models.CharField(max_length=15)),
                ('emotional_value', models.TextField(max_length=255)),
                ('review', models.TextField(max_length=1500)),
                ('mark', models.CharField(choices=[('dislike', 'dislike'), ('did not like', 'did not like'), ('neutral', 'neutral'), ('liked', 'liked'), ('loved it', 'loved it')], max_length=12)),
                ('favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
