# Generated by Django 3.2.6 on 2021-08-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='audiobook',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='length',
            field=models.IntegerField(max_length=15),
        ),
    ]
