# Generated by Django 3.2.6 on 2021-08-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='mark',
            field=models.CharField(choices=[('dislike', 'dislike'), ('did not like', 'did not like'), ('neutral', 'neutral'), ('liked', 'liked'), ('loved it', 'loved it')], max_length=12),
        ),
    ]
