# Generated by Django 3.2.5 on 2021-08-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210803_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='audiobook',
        ),
        migrations.AlterField(
            model_name='book',
            name='length',
            field=models.CharField(max_length=15),
        ),
    ]
