# Generated by Django 3.2.6 on 2021-08-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210818_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='length',
            field=models.IntegerField(),
        ),
    ]
