# Generated by Django 3.2.5 on 2021-08-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210807_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fiction', 'fiction'), ('non-fiction', 'non-fiction')], default='None', max_length=11),
        ),
    ]
