# Generated by Django 3.2.6 on 2021-08-20 17:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book_event', '0002_auto_20210812_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookevent',
            name='date_of_creation',
            field=models.DateField(default=datetime.datetime(2021, 8, 20, 17, 35, 44, 774453, tzinfo=utc)),
        ),
    ]
