# Generated by Django 3.2.6 on 2021-08-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_event', '0002_rename_events_clubevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('book_picture', models.URLField()),
                ('description', models.TextField(max_length=800)),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.DeleteModel(
            name='ClubEvents',
        ),
    ]
