# Generated by Django 3.2.6 on 2021-08-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_event', '0003_bookevent_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookevent',
            name='date_of_creation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
