# Generated by Django 3.2.6 on 2021-08-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_event', '0003_auto_20210809_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookevents',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
