# Generated by Django 3.2.6 on 2021-08-09 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_event', '0005_dislike_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookEvents',
            new_name='BookEvent',
        ),
    ]
